language: csharp
mono: none
dotnet: 2.1.4

install:
  - dotnet restore ToolBox/ToolBox.csproj
  - dotnet restore ToolBox.Tests/ToolBox.Tests.csproj
  - dotnet tool install --global dotnet-sonarscanner

script:
  - dotnet sonarscanner begin /k:"dein:toolbox" /n:"ToolBox" /v:"1.4.1" /o:"dein" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_KEY" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="$TRAVIS_BUILD_DIR/lcov.opencover.xml"
  - dotnet restore ToolBox/ToolBox.csproj
  - dotnet build ToolBox/ToolBox.csproj
  - dotnet test ToolBox.Tests/ToolBox.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover,lcov\" /p:CoverletOutput=../lcov
  - dotnet sonarscanner end /d:sonar.login="$SONAR_KEY"

after_success:
  - dotnet pack ToolBox/ToolBox.csproj /p:NuspecFile=/ToolBox/ToolBox.nuspec -o Package/ -c release
  
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push Package/dein.ToolBox.*.nupkg -k $NUGET_KEY -s $NUGET_URL
  on:
    branch: master