language: csharp
mono: none
dotnet: 2.1.401

install:
  - dotnet restore ToolBox/ToolBox.csproj
  - dotnet restore ToolBox.Tests/ToolBox.Tests.csproj

script:
  - dotnet build ToolBox/ToolBox.csproj
  - dotnet build ToolBox.Tests/ToolBox.Tests.csproj