language: csharp
mono: none
dotnet: 2.1.4

install:
  - dotnet restore ToolBox/ToolBox.csproj
  - dotnet restore ToolBox.Tests/ToolBox.Tests.csproj

script:
  - dotnet build ToolBox/ToolBox.csproj
  - dotnet build ToolBox.Tests/ToolBox.Tests.csproj
  - dotnet test ToolBox.Tests/ToolBox.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../lcov

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV
  - dotnet pack ToolBox/ToolBox.csproj /p:NuspecFile=ToolBox/ToolBox.nuspec -o Package/ -c release