name: pack

on:
  push:
    tags:
      - "v*"

env:
  dotnet: 6.0.201
  version: 1.8.0

jobs:
  pack:
    runs-on: ubuntu-latest
    name: packing
    steps:
      - uses: actions/checkout@v2
      - name: setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet }}
      - name: setup nuget config
        run: ::stop-commands::sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' "${{ github.workspace }}/Package/nuget.config" > nuget.config
      - name: create file
        run: dotnet pack ToolBox/ToolBox.csproj /p:NuspecFile=${{ github.workspace }}/ToolBox/ToolBox.nuspec -o ${{ github.workspace }}/Package/ -c release
      - name: publish nuget on microsoft
        run: dotnet nuget push "${{ github.workspace }}/Package/dein.ToolBox.${{ env.version }}.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s "nuget" --skip-duplicate --no-symbols true
      - name: publish nuget on github
        run: dotnet nuget push "${{ github.workspace }}/Package/dein.ToolBox.${{ env.version }}.nupkg" -s "github" --skip-duplicate --no-symbols true
  tweet:
    runs-on: ubuntu-latest
    name: message
    needs: pack
    steps:
      - uses: actions/checkout@v2
      - name: setup Twitter
        uses: ethomson/send-tweet-action@v1
        with:
          status: "ToolBox - C# .Net Library with utilities like: command line, files, log, platform, shell, system, transform and validation [ Win+Mac+Linux ]\n
          ${{ env.version }} 🐛🛠 version available as NuGet package\n
          $ dotnet add package dein.toolbox\n
          \n
          https://github.com/deinsoftware/toolbox"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}